image: python:latest

stages:
  - prepare
  - install
  - lint
  - test
  - imagebuild

check:
  stage: prepare
  script:
    - python -v
    - apt update -y
    - apt upgrade -y

linting:
  image: python:latest
  stage: lint
  artifacts:
    paths:
      - lint.log
    expire_in: 2 days
  allow_failure: true
  script:
    - pwd
    - pip install pylint
    - echo "aaww123w213ww" > lint.log
    - ls -all

testfile:
  stage: test
  script:
    - pwd
    - ls -all | egrep "**.py"
    - ls -all | egrep "**.log"

awscliinstall:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: install
  script:
    - aws s3 ls
    - apt update -y && apt upgrade -y
    - apt install curl gnupg software-properties-common -y
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - apt update -y && apt install terraform -y
    - terraform init
    - terraform apply -auto-approve

buildimage:
  stage: imagebuild
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker image build --pull -t ubersholder/cidocker:1 .
  script:
    - docker -v
    - docker image build --pull -t ubersholder/cidocker:1 .
    - docker image ls
    - docker push ubersholder/cidocker:1
