image: python:latest

stages:
  - configure
  - test
  - run

configure:
  script:
    - python -v
    - pip3 install awscli
    - apt update -y
    - apt upgrade -y

test:
  script:
    - ls -all | egrep "**.py"

run:
  script:
    - aws configure
    - aws s3 cp index.html s3://$S3_BUCKET/
