image: python:latest

stages:
  - prepare
  - install
  - test
  - run

prepare:
  script:
    - python -v
    - apt update -y
    - apt upgrade -y
    - apt install curl -y

install:
  script:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install

test:
  script:
    - ls -all | egrep "**.py"

run:
  script:
    - aws configure
    - aws s3 cp index.html s3://$S3_BUCKET/
