image: python:latest

stages:
  - prepare
  - install
  - test
  - terraform

check:
  stage: prepare
  script:
    - python -v
    - apt update -y
    - apt upgrade -y

testfile:
  stage: test
  script:
    - ls -all | egrep "**.py"

awscliinstall:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: install
  script:
    - aws s3 ls
    - apt update -y && apt upgrade -y
    - apt install curl gnupg software-properties-common -y
    - ls -all | egrep "**.py"
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - apt update -y && apt install terraform -y
    - terraform init
    - terraform appy
    - aws s3 cp frontend.html s3://uber-self-gitlab-serverless/
